/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface DbMon {

    }
  }

  interface HTMLDbMonElement extends StencilComponents.DbMon, HTMLStencilElement {}

  var HTMLDbMonElement: {
    prototype: HTMLDbMonElement;
    new (): HTMLDbMonElement;
  };
  interface HTMLElementTagNameMap {
    'db-mon': HTMLDbMonElement;
  }
  interface ElementTagNameMap {
    'db-mon': HTMLDbMonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'db-mon': JSXElements.DbMonAttributes;
    }
  }
  namespace JSXElements {
    export interface DbMonAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
